In [ ]:
import pandas as pd
df = pd.read_csv('/content/cleaned_job_skills.csv', on_bad_lines='skip', engine='python')
print(df.isnull().sum())
print(df.duplicated().sum())
df = df.dropna(subset=['job_skills'])
df.drop_duplicates(inplace=True)
df['job_skills'].sample(10)
df.shape
df.head()

job_link        0
job_skills    245
dtype: int64
734

,job_link,job_skills
0,Housekeeper I Pt At Jacksonville State University,"Building Custodial Services, Cleaning, Janitor..."
1,Assistant General Manager Huntington 4131 At R...,"Customer service, Restaurant management, Food ..."
2,School Based Behavior Analyst At Ccres Educati...,"Applied Behavior Analysis (ABA), Data analysis..."
3,Electrical Deputy Engineering Group Supervisor...,"Electrical Engineering, Project Controls, Sche..."
4,Electrical Assembly Lead At Sanmina,"Electrical Assembly, Point to point wiring, St..."

In [ ]:
#unique job titles and skill sets
print("Number of unique job titles:", df['job_link'].nunique())
print("Number of unique skill sets:", df['job_skills'].nunique())

Number of unique job titles: 307207
Number of unique skill sets: 451001

In [ ]:
#min, max, avg skills per job
df['num_skills'] = df['job_skills'].apply(lambda x: len(x.split(',')))
df['num_skills'].describe()

count    452181.000000
mean         20.957513
std          12.092880
min           1.000000
25%          13.000000
50%          19.000000
75%          26.000000
max         463.000000
Name: num_skills, dtype: float64

In [ ]:
#most in demand skills
from collections import Counter
all_skills = df['job_skills'].dropna().str.split(', ')
flat_skills = [skill for sublist in all_skills for skill in sublist]
skill_counts = pd.Series(Counter(flat_skills)).sort_values(ascending=False)
print(skill_counts.head(20))

Communication             126878
Teamwork                   78783
Leadership                 62018
Customer service           54888
Communication skills       41066
Customer Service           38205
Problem Solving            35849
Problemsolving             32399
Sales                      30116
Collaboration              29257
Project Management         28975
Communication Skills       28241
Attention to detail        28091
Training                   27500
Microsoft Office Suite     26746
Time management            26314
Time Management            25317
Nursing                    24980
Multitasking               22638
Microsoft Office           22155
dtype: int64